---
title: "Research"
---

## Research Interests

- Health Economics

- Policy Analysis

- Education Economics

- Applied Microeconomics

---

## Peer-reviewed Publications

1. **Zhao, H.**, & **Sun, X.** (2026). *OxyContin Reformulation and Drug-Related Arrest Rates, Property-Related Crimes, Child Maltreatment, and Food Pantry Participation.* **Frontiers in Pharmacology, 17**, 1681241.

2. Rothbart, M. W., Heflin, C., Morrissey, T. W., & **Sun, X.** (2026). *Participation Across Public Programs Among Children in Low-Income Families: Public Preschool, Child Care Subsidies, and the Supplemental Nutrition Assistance Program.* **Early Childhood Research Quarterly, 76**, 13–28.

3. **Sun, X.**, & Zhao, H. (2025). *The Impact of Anti-Bullying Laws on Children's Social-Behavioral Skills.* **Frontiers in Psychology, 16**, 1550736.

4. Zhao, H., Andreyeva, T., & **Sun, X.** (2024). *Food Security and Health Outcomes Following Gray Divorce.* **Nutrients, 16**(5), 633.

5. Heflin, C., & **Sun, X.** (2022). *Food Insecurity and the Opioid Crisis.* **The ANNALS of the American Academy of Political and Social Science, 703**(1), 262–284.

6. Andreyeva, T., **Sun, X.**, Cannon, M., & Kenney, E. (2021). *The Child and Adult Care Food Program: Barriers to Participation and Costs of Underutilization.* **Journal of Nutrition Education and Behavior, 54**(4), 327–334.

7. Andreyeva, T., & **Sun, X.** (2021). *Universal School Meals in the US: What Can We Learn from the Community Eligibility Provision?* **Nutrients, 13**(8), 2634.

8. Andreyeva, T., **Sun, X.**, Cannon, M., & Kenney, E. L. (2021). *Implementation of Minimum Nutrition Standards and Best Practices in Childcare Centers.* **Journal of the Academy of Nutrition and Dietetics, 121**(12), 2454–2463.

9. **Sun, X.**, & Andreyeva, T. (2020). *Kindergarten Entry Age and Household Food Insecurity.* **Journal of Health Behavior and Policy Review, 7**(5), 416–431.

10. Andreyeva, T., Kenney, E. L., O'Connell, M., **Sun, X.**, & Henderson, K. E. (2018). *Predictors of Nutrition Quality in Early Child Education Settings in Connecticut.* **Journal of Nutrition Education and Behavior, 50**(5), 458–467.

## Research Reports

1. Andreyeva, T., Pipito, A., **Sun, X.**, Henderson, K. E., & Powell, L. M. (2018). “Price impacts on dietary and health outcomes: a scoping review.” Final report to the World Health Organization.

## Papers Under Review or In Preparation

1. **Sun, X.** & Andreyeva, T. “The Impact of Universal Free Meals on Children’s Social Behavioral Skills and Peer Relationships.”

2. Rothbart, M., **Sun, X.**, Heflin, C., Morrissey, T. “The Impact of Public Prekindergarten Expansion on SNAP Participation: Evidence from the Virginia Preschool Initiative Plus Program.”

## Research Grants Experience

1. Robert Wood Johnson Foundation, Healthy Eating Research. Studying the Community Eligibility Provision’s Broad Impact on Child Nutrition, Health, Academics, School Attendance, and Family Food Security. 03/01/2019–08/31/2020. Principal Investigator: Tatiana Andreyeva. $150,700. Role: Research Assistant.

2. World Health Organization. Fiscal and Pricing Policies on Foods and Non-alcoholic Beverages. 04/25/2019–11/25/2019. Principal Investigator: Tatiana Andreyeva. $61,100. Role: Research Assistant.

3. Child Health and Development Institute of Connecticut (CHDI). Barriers to Participation in the Child and Adult Care Food Program in Connecticut: Opportunities for Expansion. 10/01/2017–09/30/2019. Principal Investigator: Tatiana Andreyeva. $64,998. Role: Research Assistant.

4. USDA, National Institute of Food and Agriculture (NIFA), Storrs Agricultural Experiment Station. Preference Formation and Purchasing Behavior among WIC Participating Households. 10/01/2015–09/30/2019. Principal Investigator: Tatiana Andreyeva. $60,000. Role: Research Assistant.

5. World Health Organization. Price Impacts on Dietary and Health Outcomes: A Scoping Review. 04/05/2018–06/04/2018. Principal Investigator: Tatiana Andreyeva. $21,873. Role: Research Assistant.

## Conference Presentations

- 2024 The 5th International Conference on Aging and Gerontology. “Food Security and Health Outcomes Following Gray Divorce”. Kunming, China.

- 2022 Population Association of America Annual Meeting. “Low Income Children’s Participation Across Public Programs: Public Pre-K, Child Care Subsidies, and SNAP.” Atlanta, GA.

- 2022 Population Association of America Annual Meeting. “Food Insecurity and the Opioid Crisis.” Atlanta, GA.

- 2022 Authors Conference: *The ANNALS of the American Academy of Political and Social Science*. “Food Insecurity and the Opioid Crisis.” Online.

- 2019 Second Meeting of the World Health Organization (WHO) Nutrition Guidance Expert Advisory Group (NUGAG) Subgroup on Policy Actions. “A Systematic Review on Fiscal and Pricing Policies.” Qingdao, China.

- 2019 Agricultural & Applied Economics Association (AAEA) Annual Conference. “Kindergarten Entry Age and Household Food Insecurity: Evidence from the Early Childhood Longitudinal Study.” Atlanta, GA.

## Seminar Presentations

- 2022 Syracuse University Demography and Social Policy Lab. “Low Income Children’s Participation Across Public Programs: Public Pre-K, Child Care Subsidies, and SNAP.” Syracuse, NY.

- 2022 Syracuse University Demography and Social Policy Lab. “Food Insecurity and the Opioid Crisis.” Syracuse, NY.

- 2021 Syracuse University Education and Social Policy Working Group. “The Impact of Anti-Bullying Laws on Children’s Social and Behavioral Skills.” Online.

- 2021 University of Connecticut Rudd Center for Food Policy & Obesity Seminar. “Universal School Meals in the US: What Can We Learn from the Community Eligibility Provision?” Online.

- 2019 University of Connecticut Rudd Center for Food Policy & Obesity Seminar. “Kindergarten Entry Age and Household Food Insecurity: Evidence from the Early Childhood Longitudinal Study.” Hartford, CT.

- 2018 University of Connecticut Graduate Research Forum Poster Session. “Kindergarten Entry Age and Household Food Insecurity: Evidence from the Early Childhood Longitudinal Study.” Storrs, CT.