---
title: "Teaching"
---

## Instructor

### Fall 2023

- Intro to Macroeconomics, Department of Business and Economics, Allegheny College

### Fall 2022

- Intro to Statistics (Master Level), Department of Public Administration and International Affairs, Maxwell School of Citizenship and Public Affairs, Syracuse University

### Spring 2022

- Quantitative Analysis (Master Level), Department of Public Administration and International Affairs, Maxwell School of Citizenship and Public Affairs, Syracuse University

### Fall 2019

- Macroeconomics, Department of Economics and Finance, Eastern Connecticut State University

## Teaching Assistant

### Fall 2020

- Food Policy, Department of Agricultural and Resource Economics, College of Agriculture, Health and Natural Resources, University of Connecticut

### Fall 2019

- Food Policy, Department of Agricultural and Resource Economics, College of Agriculture, Health and Natural Resources, University of Connecticut

### Fall 2018

- Food Policy, Department of Agricultural and Resource Economics, College of Agriculture, Health and Natural Resources, University of Connecticut